#!/usr/bin/env python3
"""Self-hosted fonts that reproduce exactly what each canvas board loads from Google Fonts.

Boards request different Fraunces weight sets (e.g. only 500;600). Browsers fall back to the
nearest *declared* weight, so a heading asking for 700 renders at 600 on those boards. To keep
the UI identical we declare one font-family alias per weight set, each face pointing at the same
variable font file - the same way Google's css2 API declares them.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "apps" / "web"
variants = json.loads((ROOT / "design" / "font-variants.json").read_text())

LATIN = "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
LATIN_EXT = "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"


def faces(family, weights, url_prefix):
    out = []
    for w in weights:
        for subset, rng in (("latin-ext", LATIN_EXT), ("latin", LATIN)):
            out.append(
                f"@font-face{{font-family:'{family}';font-style:normal;font-weight:{w};font-display:swap;"
                f"src:url({url_prefix}fraunces-{subset}-opsz-normal.woff2) format('woff2');unicode-range:{rng};}}"
            )
    return out


def work_sans(url_prefix):
    out = []
    for w in (400, 500, 600, 700):
        for subset, rng in (("latin-ext", LATIN_EXT), ("latin", LATIN)):
            out.append(
                f"@font-face{{font-family:'Work Sans';font-style:normal;font-weight:{w};font-display:swap;"
                f"src:url({url_prefix}work-sans-{subset}-{w}-normal.woff2) format('woff2');unicode-range:{rng};}}"
            )
    return out


app = ["/* AUTO-GENERATED by tools/gen_fonts.py */"] + work_sans("../assets/fonts/")
for v in variants:
    app += faces(v["alias"], v["weights"], "../assets/fonts/")
(WEB / "src" / "styles").mkdir(exist_ok=True)
(WEB / "src" / "styles" / "fonts.css").write_text("\n".join(app) + "\n")

# Harness copies (family name "Fraunces", exactly like Google) used to render the original boards.
h = WEB / "visual" / "harness"
h.mkdir(parents=True, exist_ok=True)
for v in variants:
    css = work_sans("../../src/assets/fonts/") + faces("Fraunces", v["weights"], "../../src/assets/fonts/")
    (h / f"fonts-{'-'.join(map(str, v['weights']))}.css").write_text("\n".join(css) + "\n")
print("fonts ok:", [v["alias"] for v in variants])
