"""Screen registry: every finalized canvas board, its route and its portal group.

This is the single source of truth that ties a design board to a route in the web app.
"""

SCREENS = [
    # id (= board file name without .dc.html), route, group
    ("Main-Editorial", "/", "public"),
    ("Properties", "/properties", "public"),
    ("InvestByROI", "/invest", "public"),
    ("BuildAHome", "/build", "public"),
    ("ForDealers", "/for-dealers", "public"),
    ("ForBuilders", "/for-builders", "public"),

    ("Advisor-Wizard", "/advisor", "advisor"),
    ("Advisor-LeadCapture", "/advisor/send-offers", "advisor"),
    ("Advisor-Results", "/advisor/submitted", "advisor"),

    ("Estimator-DesignGallery", "/estimator", "estimator"),
    ("Estimator-Services", "/estimator/services", "estimator"),
    ("Estimator-Signup", "/estimator/signup", "estimator"),
    ("Estimator-Results", "/estimator/results", "estimator"),
    ("BuildAdvisor-Services", "/build-advisor/services", "estimator"),
    ("BuildAdvisor-Confirmation", "/build-advisor/confirmation", "estimator"),

    ("Customer-Login", "/login", "customer"),
    ("Customer-ActivateAccount", "/activate", "customer"),
    ("Customer-Portal", "/customer", "customer"),
    ("Customer-Offers", "/customer/offers", "customer"),
    ("Customer-Resell", "/customer/resell", "customer"),
    ("Customer-BuildProject", "/customer/build-project", "customer"),

    ("Dealer-Dashboard", "/dealer", "dealer"),
    ("Dealer-AddProperty", "/dealer/properties/new", "dealer"),
    ("Dealer-Customers", "/dealer/customers", "dealer"),
    ("Dealer-CreateInstallmentPlan", "/dealer/installment-plans/new", "dealer"),
    ("Dealer-BuyerRequests", "/dealer/buyer-requests", "dealer"),
    ("Dealer-TransferRequests", "/dealer/transfer-requests", "dealer"),
    ("Dealer-Reminders", "/dealer/reminders", "dealer"),
    ("Dealer-CustomerOffers", "/dealer/offers", "dealer"),
    ("Dealer-Marketing-Email", "/dealer/marketing/email", "dealer"),
    ("Dealer-Marketing-EmailEditor", "/dealer/marketing/email/editor", "dealer"),
    ("Dealer-Marketing-SMS", "/dealer/marketing/sms", "dealer"),
    ("Dealer-Marketing-ImportContacts", "/dealer/marketing/import", "dealer"),

    ("Provider-Dashboard", "/provider", "provider"),

    ("SuperAdmin-Dashboard", "/admin", "admin"),
    ("SuperAdmin-Approvals", "/admin/approvals", "admin"),
    ("SuperAdmin-DealerFeatureAccess", "/admin/feature-access", "admin"),
    ("SuperAdmin-DealerCredibility", "/admin/credibility", "admin"),
    ("SuperAdmin-Customers", "/admin/customers", "admin"),
    ("SuperAdmin-AIScraper", "/admin/ai-scraper", "admin"),
    ("SuperAdmin-AIProviderSettings", "/admin/ai-providers", "admin"),
]

GROUP_HOME = {
    "public": "/", "advisor": "/", "estimator": "/",
    "customer": "/customer", "dealer": "/dealer", "provider": "/provider", "admin": "/admin",
}

# ---- Navigation wiring -------------------------------------------------------
# Label (normalised button/link text) -> route. Looked up per group first, then "*".
# Anything not listed stays inert until its behaviour is built in a later phase.
LINKS = {
    "*": {
        "Properties": "/properties",
        "Properties Invest by ROI": "/properties",
        "Invest by ROI": "/invest",
        "Build a Home": "/build",
        "For Dealers": "/for-dealers",
        "For Builders": "/for-builders",
        "Installment Plans": "/properties",
        "Log In": "/login",
        "Log in": "/login",
        "List a Property": "/for-dealers",
        "Start an Estimate": "/estimator",
        "Refine My Estimate": "/estimator",
        "Browse Design Gallery": "/estimator",
        "See Full Gallery": "/estimator",
        "Get Matched": "/advisor",
        "Start Matching": "/advisor",
        "See Matches": "/advisor",
        "Try the Property Advisor": "/advisor",
        "New here? Try the Property Advisor": "/advisor",
        "Submit to Dealers to Bid Their Offers": "/advisor",
        "See Sample Matches": "/properties",
        "See How It Works": "/invest",
        "See How Plans Work": "/properties",
        "Register as a Dealer": "/login",
        "Register Your Practice": "/login",
        "See Dealer Dashboard": "/dealer",
        "See Provider Dashboard": "/provider",
        "Build a Quote": "/provider",
        "Open Email Templates": "/dealer/marketing/email",
        "Send Campaign": "/dealer/marketing/email",
        "Edit with AI": "/dealer/marketing/email/editor",
        "Open SMS Templates": "/dealer/marketing/sms",
        "Open Payment Reminders": "/dealer/reminders",
        "Open Send Offers": "/dealer/offers",
        "Send to 86 Matched Buyers": "/dealer/offers",
        "Open Import Contacts": "/dealer/marketing/import",
        "Confirm & Import": "/dealer/marketing/import",
        "See Offer": "/customer/offers",
        "Compare & Accept": "/customer/offers",
        "See My Offers": "/customer/offers",
    },
    "advisor": {
        "Submit My Request to Dealers": "/advisor/send-offers",
        "Send My Request": "/advisor/submitted",
        "Edit criteria": "/advisor",
        "Browse Listings While You Wait": "/properties",
        "Go to My Offers": "/customer/offers",
    },
    "estimator": {
        "Continue": "/estimator/services",
        "Change": "/estimator",
        "See My Estimate": "/estimator/signup",
        "Show My Estimate": "/estimator/results",
        "Request Actual Quotes": "/build-advisor/services",
        "Continue to Send Request": "/build-advisor/confirmation",
        "Go to My Build Project": "/customer/build-project",
        "Browse Verified Providers": "/for-builders",
    },
    "customer": {
        "Log In": "/customer",
        "Verify & Activate Account": "/customer",
        "Sell This Property": "/customer/resell",
        "Back to My Properties": "/customer",
        "Cancel": "/customer",
        "Submit for Dealer Approval": "/customer",
        "Accept Offer": "/customer",
        "My Properties": "/customer",
        "My Offers": "/customer/offers",
        "My Build Project": "/customer/build-project",
        "Resale Requests": "/customer/resell",
        "Payments": "/customer",
    },
    "dealer": {
        "Dashboard": "/dealer",
        "Buyer Requests": "/dealer/buyer-requests",
        "Transfer Requests": "/dealer/transfer-requests",
        "Properties": "/dealer/properties/new",
        "My Properties": "/dealer/properties/new",
        "Customers": "/dealer/customers",
        "Installment Plans": "/dealer/installment-plans/new",
        "Payments": "/dealer/reminders",
        "Reminders": "/dealer/reminders",
        "Customer Offers": "/dealer/offers",
        "Marketing": "/dealer/marketing/email",
        "Email Marketing": "/dealer/marketing/email",
        "SMS Marketing": "/dealer/marketing/sms",
        "+ Add Property": "/dealer/properties/new",
        "+ Create Installment Plan": "/dealer/installment-plans/new",
        "Activate Plan": "/dealer/customers",
        "Cancel": "/dealer/customers",
        "Publish Property": "/dealer",
        "Templates": "/dealer/marketing/email",
        "Marketing ": "/dealer/marketing/email",
        "Use Template": "/dealer/marketing/email/editor",
    },
    "provider": {
        "Incoming Requests": "/provider",
    },
    "admin": {
        "Dashboard": "/admin",
        "Dealer Approvals": "/admin/approvals",
        "All Dealers": "/admin/feature-access",
        "Dealer Credibility": "/admin/credibility",
        "Customers": "/admin/customers",
        "AI Scraper & Onboarding": "/admin/ai-scraper",
        "AI Provider Settings": "/admin/ai-providers",
        "Save & Approve Dealer": "/admin/approvals",
        "Cancel": "/admin/approvals",
    },
}

# Per-screen overrides (label -> route or None to force inert).
OVERRIDES = {
    # Buttons drawn inside product "snapshots" on marketing pages are pictures of the tool - not links.
    "ForDealers": {"Send Campaign": None, "Edit with AI": None, "Send to 86 Matched Buyers": None, "Confirm & Import": None},
    "ForBuilders": {"Build a Quote": None},
    "Main-Editorial": {"Compare & Accept": None, "See My Offers": None},
    "Properties": {"Compare & Accept": None, "See Offer": "/advisor"},
    # Actions whose behaviour arrives in a later phase stay inert rather than faking success.
    "Customer-Offers": {"Accept Offer": None},
    "Customer-Resell": {"Submit for Dealer Approval": None},
    "Customer-ActivateAccount": {"Verify & Activate Account": None},
    "Dealer-CreateInstallmentPlan": {"Activate Plan": None},
    "Dealer-Marketing-SMS": {"Use Template": None},
    "Advisor-Wizard": {"Back": "/"},
    "Advisor-LeadCapture": {"Back": "/advisor"},
    "Estimator-Services": {"Back": "/estimator"},
    "BuildAdvisor-Services": {"Back": "/estimator/results"},
    "Dealer-Marketing-EmailEditor": {"Templates": "/dealer/marketing/email"},
    "Dealer-Marketing-ImportContacts": {"Marketing": "/dealer/marketing/email"},
}

# Dealer sidebar label -> the feature an admin can lock (Dashboard, Settings, Customer Offers are always on).
DEALER_FEATURE_BY_LABEL = {
    "Buyer Requests": "buyer_requests",
    "Transfer Requests": "transfer_requests",
    "Properties": "properties",
    "My Properties": "properties",
    "Customers": "customers_plans",
    "Installment Plans": "customers_plans",
    "Payments": "payments_reminders",
    "Reminders": "payments_reminders",
    "Marketing": "marketing",
    "Branding": "branding",
}
